name: Schedule Python Script

on:
  schedule:
    # Schedule the script using cron syntax (e.g., every day at midnight)
     - cron: '0 16-22 * * 1-5'  # Weekdays (Monday to Friday) from 16:00 to 22:00
     - cron: '0 9-20 * * 6-7'   # Weekends (Saturday and Sunday) from 09:00 to 20:00
  workflow_dispatch: # Allows manual triggering of the workflow
    {}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install garminconnect
        pip install -r requirements.txt # Ensure your repo has a requirements.txt file if dependencies are needed

    - name: Run Python script
      run: |
        python main.py
